json.id item.id
json.product_id item.product_id
json.product_name item.product_name
json.product_category item.product_category
json.product_dynamic_price item.product_dynamic_price.to_f
json.product_total_reserved item.product_total_reserved
json.product_total_inventory item.product_total_inventory
json.subtotal item.subtotal
json.quantity item.quantity
