compare_sinatra_pricing:
  class: "CompareSinatraPricingJob"
  queue: "default"
  cron: "0 * * * *" # every hour

update_prev_demand_count:
  cron: "0 */2 * * *" # every 2 hours
  class: UpdatePrevDemandCountJob
  queue: default

monitor_high_inventory:
  class: "MonitorHighInventoryJob"
  queue: "default"
  cron: "0 0 * * *" # at 12:00 AM
