compare_sinatra_pricing:
  class: "CompareSinatraPricingJob"
  queue: "default"
  cron: "0 * * * *" # every hour

monitor_high_inventory:
  class: "MonitorHighInventoryJob"
  queue: "default"
  cron: "0 * * * *" # every hour
